name: emoj
version: '0.3.0'
summary: emoj
description: |
  Find relevant emoji from text on the command-line.

grade: stable
confinement: strict

apps:
  emoj:
    command: bin/emoj
    plugs: [network]

parts:
  emoj:
    plugin: nodejs
    source: .
